import { Scale } from 'tonal';

export const GuitarConstants = Object.freeze({
  minimumFrets: 2,
  maximumFrets: 25,
  notesFlat: ['A', 'Bb', 'B', 'C', 'Db', 'D', 'Eb', 'E', 'F', 'Gb', 'G', 'Ab'],
  notesSharp: ['A', 'A#', 'B', 'C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#'],
  tuning: [
    [7, 14, 10, 5, 12, 7],
    [6, 13, 9, 4, 11, 6],
    [7, 2, 11, 7, 2, 7],
    [7, 3, 10, 3, 10, 3],
    [5, 14, 10, 5, 10, 5],
    [5, 12, 9, 5, 12, 5],
    [7, 14, 10, 5, 12, 5],
    [2, 5, 9, 12, 16, 19],
    [1, 5, 8, 12, 15, 19],
    [7, 10, 7, 7, 10, 7],
    [2, 5, 2, 5, 2, 5],
    [5, 8, 5, 4, 3, 5],
    [7, 10, 7, 10, 7, 10],
    [0, 0, 0, 7, 7, 0],
  ],
  scaleNames: Scale.names(),
  tuningNames: [
    'Standard',
    'Half-Step Down',
    'Open G',
    'DADGAD',
    'Drop C',
    'Double Drop D',
    'Open D Minor',
    'Drop D',
    'Open C',
    'All Fourths',
    'New Standard',
    'Dropped A',
    'Open E',
    'Open D',
  ],
  guitars: [
    'acoustic_guitar_nylon',
    'acoustic_guitar_steel',
    'electric_guitar_clean',
    'electric_guitar_jazz',
    'electric_guitar_muted',
    'overdriven_guitar',
    'distortion_guitar',
    'guitar_harmonics',
    "accordion",
    "acoustic_bass",
    "acoustic_grand_piano",
    "agogo",
    "alto_sax",
    "applause",
    "bagpipe",
    "banjo",
    "baritone_sax",
    "bassoon",
    "bird_tweet",
    "blown_bottle",
    "brass_section",
    "breath_noise",
    "bright_acoustic_piano",
    "celesta",
    "cello",
    "choir_aahs",
    "church_organ",
    "clarinet",
    "clavinet",
    "contrabass",
    "drawbar_organ",
    "dulcimer",
    "electric_bass_finger",
    "electric_bass_pick",
    "electric_grand_piano",
    "electric_piano_1",
    "electric_piano_2",
    "english_horn",
    "fiddle",
    "flute",
    "french_horn",
    "fretless_bass",
    "fx_1_rain",
    "fx_2_soundtrack",
    "fx_3_crystal",
    "fx_4_atmosphere",
    "fx_5_brightness",
    "fx_6_goblins",
    "fx_7_echoes",
    "fx_8_scifi",
    "glockenspiel",
    "guitar_fret_noise",
    "gunshot",
    "harmonica",
    "harpsichord",
    "helicopter",
    "honkytonk_piano",
    "kalimba",
    "koto",
    "lead_1_square",
    "lead_2_sawtooth",
    "lead_3_calliope",
    "lead_4_chiff",
    "lead_5_charang",
    "lead_6_voice",
    "lead_7_fifths",
    "lead_8_bass__lead",
    "marimba",
    "melodic_tom",
    "music_box",
    "muted_trumpet",
    "oboe",
    "ocarina",
    "orchestra_hit",
    "orchestral_harp",
    "pad_1_new_age",
    "pad_2_warm",
    "pad_3_polysynth",
    "pad_4_choir",
    "pad_5_bowed",
    "pad_6_metallic",
    "pad_7_halo",
    "pad_8_sweep",
    "pan_flute",
    "percussive_organ",
    "piccolo",
    "pizzicato_strings",
    "recorder",
    "reed_organ",
    "reverse_cymbal",
    "rock_organ",
    "seashore",
    "shakuhachi",
    "shamisen",
    "shanai",
    "sitar",
    "slap_bass_1",
    "slap_bass_2",
    "soprano_sax",
    "steel_drums",
    "string_ensemble_1",
    "string_ensemble_2",
    "synth_bass_1",
    "synth_bass_2",
    "synth_brass_1",
    "synth_brass_2",
    "synth_choir",
    "synth_drum",
    "synth_strings_1",
    "synth_strings_2",
    "taiko_drum",
    "tango_accordion",
    "telephone_ring",
    "tenor_sax",
    "timpani",
    "tinkle_bell",
    "tremolo_strings",
    "trombone",
    "trumpet",
    "tuba",
    "tubular_bells",
    "vibraphone",
    "viola",
    "violin",
    "voice_oohs",
    "whistle",
    "woodblock",
    "xylophone",
  ],
  tunings: [
    {
      name: 'Standard',
      notes: ['e', 'a', 'd', 'g', 'b', 'e'],
      tuning: [7, 14, 10, 5, 12, 7],
    },
    {
      name: 'Half-Step Down',
      notes: ['eb', 'ab', 'db', 'gb', 'bb', 'eb'],
      tuning: [6, 13, 9, 4, 11, 6],
    },
    {
      name: 'DADGAD',
      notes: ['d', 'a', 'd', 'g', 'a', 'd'],
      tuning: [5, 12, 10, 5, 12, 5],
    },
    {
      name: 'Open G',
      notes: ['d', 'g', 'd', 'g', 'b', 'd'],
      tuning: [5, 14, 10, 5, 10, 5],
    },
    {
      name: 'Drop C',
      notes: ['c', 'g', 'c', 'f', 'a', 'd'],
      tuning: [5, 12, 8, 3, 10, 3],
    },
    {
      name: 'Drop D',
      notes: ['d', 'a', 'd', 'g', 'b', 'e'],
      tuning: [5, 10, 7, 3, 12, 5],
    },
    {
      name: 'Open C',
      notes: ['c', 'g', 'c', 'g', 'c', 'e'],
      tuning: [8, 3, 8, 3, 8, 12],
    },
    {
      name: 'All Fourths',
      notes: ['e', 'a', 'd', 'g', 'c', 'f'],
      tuning: [7, 12, 7, 2, 9, 4],
    },
    {
      name: 'New Standard',
      notes: ['c', 'f', 'a#', 'd#', 'g', 'c'],
      tuning: [8, 13, 10, 3, 8, 1],
    },
    // {
    //   name: 'Open D',
    //   notes: ['d', 'a', 'd', 'f#', 'a', 'd'],
    //   tuning: [2, 14, 11, 6, 9, 2],
    // },
    // {
    //   name: 'Open E',
    //   notes: ['e', 'b', 'e', 'g#', 'b', 'e'],
    //   tuning: [4, 11, 7, 2, 11, 4],
    // },
    // {
    //   name: 'Dropped A',
    //   notes: ['a', 'e', 'a', 'd', 'f#', 'b'],
    //   tuning: [9, 14, 9, 4, 7, 11],
    // },
    // {
    //   name: 'New Standard',
    //   notes: ['c', 'f', 'a#', 'd#', 'g', 'c'],
    //   tuning: [8, 13, 10, 3, 8, 1],
    // },
    // {
    //   name: 'All Fourths',
    //   notes: ['e', 'a', 'd', 'g', 'c', 'f'],
    //   tuning: [7, 12, 7, 2, 9, 4],
    // },
    // {
    //   name: 'Open C',
    //   notes: ['c', 'g', 'c', 'g', 'c', 'e'],
    //   tuning: [8, 3, 8, 3, 8, 12],
    // },
  ],
});

export default GuitarConstants;
